[package]
name = "azothacore-tools-sqltable-dump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx.workspace = true
tokio.workspace = true
flate2.workspace = true
