[workspace]
resolver = "2"
members = ["crates/*", "azothacore-script-modules/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
lto = true

[workspace.dependencies]
# Local crates
azothacore-tools = { path = "crates/azothacore-tools" }
azothacore-server = { path = "crates/azothacore-server" }
azothacore-common = { path = "crates/azothacore-common" }
azothacore-modules = { path = "azothacore-script-modules/modules" }
casclib-sys = { path = "crates/casclib-sys" }
wow-db2 = { path = "crates/wow-db2" }
wow-db2-proc-macros = { path = "crates/wow-db2-proc-macros" }
# External crates
clap =  { version = "4.1.8", features = ["derive"] }
flagset = { version = "0.4.3", features = ["serde"] }
futures = "0.3.27"
num-traits = { version = "0.2.15" }
num-derive = { version = "0.3.3" }
num = { version = "0.4.1" }
thiserror = { version = "1.0.40" }
serde = { version = "1.0.152", features = ["derive"] }
toml = { version = "0.7.2", features = ["preserve_order"] }
serde_default = "0.1.0"
serde-inline-default = "0.1.1"
sqlx = { version = "0.6.2", features = [ "runtime-tokio-rustls", "mysql", "time"] }
nalgebra = { version = "0.32.2", features = [ "serde-serialize" ] }
parry3d = { version = "0.13.5", features = ["serde-serialize"] }
tokio = { version = "1.26.0", features = ["full", "tracing"] }
tracing = { version = "0.1.37" }
recastnavigation-sys = { version = "1.0.1", features = [ "detour", "recast", "detour_large_nav_meshes" ] }
walkdir = { version = "2.3.3" }
rand = { version = "0.8.5" }
num-bigint = { version = "0.4.3", features = ["rand"] }
