[toolchain]
channel = "nightly"
components = [
    "cargo",
    "clippy",
    "rust-docs",
    "rust-src",
    "rust-std",
    "rustfmt",
    "rustc",
    "llvm-tools-preview",
    "rust-analyzer",
]
